name: Examples

on: [push]

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - name: Install Logicrom platform
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Clone Arduino build test application
        uses: actions/checkout@v4
        with:
          repository: 'waybyte/arduino-verify'
          path: app/arduino-verify
      - name: Build Arduino
        run: |
          pio run -d app/arduino-verify
      - name: Clone Logicrom OpenCPU SDK build test application
        uses: actions/checkout@v4
        with:
          repository: 'waybyte/logicromsdk-verify'
          path: app/logicromsdk-verify
      - name: Build Logicrom OpenCPU SDK
        run: |
          pio run -d app/logicromsdk-verify
  build:
    needs: verify
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11]
        example:
          - "examples/arduino-blink"
          - "examples/example-adc"
          - "examples/example-console"
          - "examples/example-display"
          - "examples/example-gpio"
          - "examples/example-gps"
          - "examples/example-httpclient"
          - "examples/example-i2c"
          - "examples/example-os"
          - "examples/example-pwm"
          - "examples/example-socket"
          - "examples/example-spi"
          - "examples/example-ssl-socket"
          - "examples/example-ssl-socket-clientauth"
          - "examples/example-timer"
          - "examples/example-uart"
          - "examples/hello-world"
          - "examples/logicromsdk-blink"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Logicrom platform and examples
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
