name: Examples

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]
        example:
          - "examples/arduino-blink"
          - "examples/gpio-blink"
          - "examples/adc-example"
          - "examples/socket-example"
          - "examples/ssl-socket-example"
          - "examples/ssl-socket-clientauth"
          - "examples/example-console"
          - "examples/example-display"
          - "examples/example-gpio"
          - "examples/example-gps"
          - "examples/example-httpclient"
          - "examples/example-i2c"
          - "examples/example-os"
          - "examples/example-pwm"
          - "examples/example-spi"
          - "examples/example-timer"
          - "examples/example-uart"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Logicrom platform and examples
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}
